# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('primary', '初级'), ('middle', '中级'), ('advanced', '高级')], default='primary', max_length=20, verbose_name='课程等级'),
        ),
    ]
