# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='fav_type',
            field=models.SmallIntegerField(choices=[(1, '课程'), (2, '机构'), (3, '讲师')], default=1, verbose_name='收藏类型'),
        ),
    ]
