# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-27 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
    ]
