# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190127_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('reg', '注册'), ('fgt', '找回密码'), ('upd', '修改邮箱')], max_length=10, verbose_name='发送类型'),
        ),
    ]
