"""
Django settings for StudyOnline project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '82bb(+rc8fx-j)%&f59_u6dul3*=us58mzeza@h3-9=k3)p#e5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    'org.apps.OrgConfig',
    'course.apps.CourseConfig',
    'operation.apps.OperationConfig',
    'xadmin',
    'crispy_forms',
    'DjangoUeditor',
    'captcha',
    'pure_pagination',


]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StudyOnline2.urls'

AUTH_USER_MODEL = 'user.UserProfile'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',     # 配置媒体文件上下文
                # 如果不处理媒体文件，前端{{MEDIA_URL}}值将为空
            ],
        },
    },
]

WSGI_APPLICATION = 'StudyOnline2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'study_online2',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'init_command': 'SET default_storage_engine=INNODB;'}
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

"""
开启生产环境后，django会默认为你的静态资源会用代理服务器，所以上面的MEDIA_URL将不起作用。
我们需要自己配置静态文件目录。
还需要在urls文件中加入：url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
"""
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 发送email配置
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "jevoly@163.com"
EMAIL_HOST_PASSWORD = "33116803209501"
EMAIL_USE_TLS = False
EMAIL_FROM = "jevoly@163.com"

# 上传路径配置
# 用户
USER_UPLOAD = {
    # 用户头像
    'AVATAR': {
        # 上传路径
        'UPLOAD': 'user/avatar/%Y/%m',
        # 默认图片
        'DEFAULT': 'user/avatar/default.png'
    }

}
# 轮转图
BANNER_UPLOAD = {
    # 首页轮转图
    'INDEX': 'index/banner/%Y/%m'
}
# 机构
ORG_UPLOAD = {
    # 机构logo
    'LOGO': {
        'UPLOAD': 'org/logo/%Y/%m',
        'DEFAULT': 'org/logo/default.png'
    }
}
# 教师
TEACHER_UPLOAD = {
    'AVATAR': {
        'UPLOAD': 'teacher/avatar/%Y/%m',
        'DEFAULT': 'teacher/avatar/default.png'
    }
}
# 课程
COURSE_UPLOAD = {
    # 课程详情
    'DETAIL': {
        'IMAGE': 'course/detail/images/',
        'FILE': 'course/detail/files/'
    },
    # 课程封面
    'COVER': {
        'UPLOAD': 'course/cover/%Y/%m',
        'DEFAULT': 'course/cover/default.png'
    },
    # 课程资源
    'RESOURCE': {
        'UPLOAD': 'course/resource/%Y/%m'
    }
}


