# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名')),
                ('desc', models.TextField(verbose_name='机构描述')),
                ('category', models.CharField(choices=[('px', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='px', max_length=5, verbose_name='机构类别')),
                ('address', models.CharField(max_length=150, verbose_name='机构地址')),
                ('logo', models.ImageField(default='org/logo/default.png', upload_to='org/logo/%Y/%m', verbose_name='机构Logo')),
                ('tag', models.CharField(max_length=20, verbose_name='机构标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('stu_nums', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数量')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='讲师名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='male', max_length=5, verbose_name='讲师性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar', models.ImageField(default='teacher/avatar/default.png', upload_to='teacher/avatar/%Y/%m', verbose_name='讲师头像')),
                ('work_years', models.SmallIntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('work_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('teach_feature', models.CharField(max_length=100, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set([('org', 'name', 'gender', 'birthday')]),
        ),
        migrations.AlterUniqueTogether(
            name='org',
            unique_together=set([('name', 'city', 'address')]),
        ),
    ]
