# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='城市名'),
        ),
    ]
