# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_org_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='male', max_length=10, verbose_name='讲师性别'),
        ),
    ]
